services:
  app:
    image: ghcr.io/mohsendro/wordpress-bedrock-php-fpm:${IMAGE_TAG}
    build: null
    volumes:
      - uploads:/app/web/app/uploads
    restart: always

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./:/app:ro
      - uploads:/app/web/app/uploads
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  wp-cli:
    image: ghcr.io/mohsendro/wordpress-bedrock-php-fpm:${IMAGE_TAG}
    build: null
    working_dir: /app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
      - uploads:/app/web/app/uploads
    entrypoint: ["wp"]
    profiles: ["tools"]
